### ISSUE TITLE
[BUG] Page wrap setting doesn't apply

### ISSUE THREAD

**Issue by Akababa** [bengarrett/RetroTxt#160]
**Describe the bug**
In the options page, when I turn on page wrapping and refresh a file:// tab, it is still off (I can still toggle it on and off). Same happens if it toggle it on in the file:// tab and refresh. It persists in the options page though.

**To Reproduce**
1. Open a file:// tab
2. Turn on column wrap in this tab or go to the settings and turn it on
3. Refresh the file:// tab
4. See that column wrap is turned off in the file:// tab

**Screenshots**

**RetroTxt (access Options and click the about tab)**
- 5.1.0

**Browser (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 110.0.5481.177 (Official Build) (64-bit) 

**Additional context**

**Comment by bengarrett** [comment]
Hi @Akababa, thanks for the report. I can confirm this behavior and will look to a fix for the next update.

**Comment by bengarrett** [comment]
Fixed for the next release.

**Comment by Akababa** [comment]
I think this is still not working in 5.2.0. If I turn on page wrap in the options and then open a new file:// tab, the page wrap is off (but the setting is persisted in the options page).

**Comment by bengarrett** [comment]
Thanks, I'll open a new issue.
